spring:
  datasource:
    url: jdbc:mysql://mysql:3306/test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  redis:
    redisson:
      file: classpath:redisson_single.yaml
