logging:
  level:
    root: INFO
server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  data:
    redis:
      host: localhost
      port: 6379
  redis:
    redisson:
      file: classpath:redisson_single.yaml
