/*
 * This file was generated by the Gradle 'init' task.
 */
plugins {
    id("org.yqj.source.java-library-conventions")
}

publishing {
    publications {
        getByName<MavenPublication>("maven") {
            pom {
                description.set("org yqj source spring info")
            }
        }
    }
}

