/*
 * This file was generated by the Gradle 'init' task.
 */
plugins {
    id("org.yqj.source.java-spring-conventions")
}

publishing {
    publications {
        getByName<MavenPublication>("maven") {
            pom {
                description.set("org yqj source spring info")
            }
        }
    }
}

dependencies {
    implementation("org.springframework.boot:spring-boot-starter-web")

    // database
    implementation("com.mysql:mysql-connector-j")
    implementation("com.baomidou:mybatis-plus-spring-boot3-starter:3.5.6")
    implementation("com.baomidou:mybatis-plus-extension:3.5.6")

    // redis
    implementation("org.redisson:redisson-spring-boot-starter:3.28.0")

    // dubbo
    implementation(platform("org.apache.dubbo:dubbo-bom:3.3.0-beta.1"))

    implementation("org.apache.dubbo:dubbo-spring-boot-starter")
    implementation("org.apache.dubbo:dubbo-nacos-spring-boot-starter")
//    implementation("org.apache.dubbo:dubbo-zookeeper-curator5-spring-boot-starter")

    implementation("org.apache.dubbo:dubbo-serialization-fastjson2")

    implementation(project(":api"))
}